require 'rails_helper'

RSpec.describe GetSongListFromDescription do

  
  describe '#run' do
    let(:description_one) {
      "POV: You are in '80s Japan at a disco during warm summer night 💃

      This is an updated and extended version of my previous video!
      
      ☕If You enjoyed my work - buy me a coffee☕
      link: https://www.buymeacoffee.com/vagabond_db
      
      Daily AI art here!  
      🔵 Twitter 🔵
      
      
      / vagabond_twt  
      🟣 Instagram 🟣
      
      
      / vagabond_db  
      🔴 Pinterest 🔴
      
      
      / vagabond_db  
      
      🟢 My Spotify 🟢
      link: https://open.spotify.com/user/31fjfp7...
      
      tracklist:
      00:00 Stay With Me - Miki Matsubara
      05:44 Lady Sunshine - Anri
      09:24 Airport Lady - Toshiki Kadomatsu
      13:38 Sweet Love - Junko Ohashi
      18:28 Shyness Boy - Anri
      21:45 Last Summer Whisper - Anri
      26:45 Street Dancer - Hiromi Iwasaki
      31:53 Summer Suspicion - S. Kiyotaka & Omega Tribe
      36:27 Windy Summer - Anri
      40:36 Cupid - Miki Matsubara
      45:56 Twilight Bay City - S. Kiyotaka & Omega Tribe
      50:08 Older Girl - Omega Tribe
      54:25 - Oh no, Oh Yes - Mariya Takeuchi
      59:39 Remember Summer Days - Anri
      01:04:35 Bay City - Junko Yagami
      01:08:46 Just a Joke - Yurie Kokubu
      
      All of the art in the video is generated by Midjourney.
      
      I do not own rights to any music used in this video. Please, support the artists!"
    }
    
    it 'parses the description and returns a list of songs' do
      subject = described_class.new
      expected_result = [
        { start_time: "00:00", end_time: "05:44", title: "Stay With Me - Miki Matsubara" },
        { start_time: "05:44", end_time: "09:24", title: "Lady Sunshine - Anri" },
        { start_time: "09:24", end_time: "13:38", title: "Airport Lady - Toshiki Kadomatsu" },
        { start_time: "13:38", end_time: "18:28", title: "Sweet Love - Junko Ohashi" },
        { start_time: "18:28", end_time: "21:45", title: "Shyness Boy - Anri" },
        { start_time: "21:45", end_time: "26:45", title: "Last Summer Whisper - Anri" },
        { start_time: "26:45", end_time: "31:53", title: "Street Dancer - Hiromi Iwasaki" },
        { start_time: "31:53", end_time: "36:27", title: "Summer Suspicion - S. Kiyotaka & Omega Tribe" },
        { start_time: "36:27", end_time: "40:36", title: "Windy Summer - Anri" },
        { start_time: "40:36", end_time: "45:56", title: "Cupid - Miki Matsubara" },
        { start_time: "45:56", end_time: "50:08", title: "Twilight Bay City - S. Kiyotaka & Omega Tribe" },
        { start_time: "50:08", end_time: "54:25", title: "Older Girl - Omega Tribe" },
        { start_time: "54:25", end_time: "59:39", title: "- Oh no, Oh Yes - Mariya Takeuchi" },
        { start_time: "59:39", end_time: "01:04:35", title: "Remember Summer Days - Anri" },
        { start_time: "01:04:35", end_time: "01:08:46", title: "Bay City - Junko Yagami" },
        { start_time: "01:08:46", end_time: nil, title: "Just a Joke - Yurie Kokubu" },
      ]



      expect(subject.run(description_one)).to eq(expected_result)
    end
  end
end
